[project]
name = "kubeler"
version = "0.1.2"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jinja2>=3.1.5",
    "kubernetes>=32.0.0",
    "pydantic>=2.10.6",
    "python-dotenv>=1.0.1",
]
