#cmd: kubectl -n support apply -f registry-secret.yaml
#cmd: kubectl -n staging apply -f registry-secret.yaml
#cmd: kubectl -n production apply -f registry-secret.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
data:
  .dockerconfigjson: {{ secret }}
type: kubernetes.io/dockerconfigjson