# install cert manager
#cmd: helm repo add jetstack https://charts.jetstack.io
#cmd: helm install cert-manager jetstack/cert-manager --namespace cert-manager --version v1.17.0 --set installCRDs=true

#cmd: kubectl apply -f letsencrypt-issuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ email }}
    privateKeySecretRef:
      name: letsencrypt-issuer
    solvers:
      - http01:
          ingress:
            class: {{ ingress_class }}